name: tunerstudio
version: 3.1.04
summary: TunerStudio MS - an advanced MegaSquirt Tuning Software
description: |
  TunerStudio MS, the most most advanced and refined MegaSquirt Tuning software available.
  The registered and Lite! editions are the same installer. 
  
  BETA edition.

  After installing, run the following commands:
  
  sudo snap connect tunerstudio:raw-usb
  sudo snap connect tunerstudio:removable-media
  sudo snap connect tunerstudio:bluez
  sudo snap connect tunerstudio:bluetooth-control
  
  This is NOT an officially supported snap from TunerStudio. It is basically an automated
  installer for the software on 64-bit Linux systems running snapd. 

base: core18
grade: stable
confinement: strict
compression: lzo

assumes: 
  - command-chain
  
architectures:
  - build-on: amd64

apps:
  tunerstudio: 
    extensions: 
      - gnome-3-34
    command: launch
    command-chain: 
      - bin/homeishome-launch    
    plugs:
      - network
      - network-bind
      - home
      - raw-usb
      - removable-media
      - browser-support
      - audio-playback
      - pulseaudio  # compatibility with snapd <2.41
      - x11
      - desktop
      - desktop-legacy
      - bluez
      - bluetooth-control
    environment: 
      JAVA_HOME: $SNAP/usr/lib/jvm/java-1.8.0-openjdk-amd64   
      PYTHONPATH: $SNAP_DESKTOP_RUNTIME/usr/lib/python3.6/dist-packages
      
parts:
  tool:
    plugin: nil
    build-packages:
      - openjdk-8-jre-headless
      - librxtx-java
      - ca-certificates
      - ca-certificates-java
      
  homeishome-launch:
    plugin: nil
    stage-snaps:
      - homeishome-launch         
      
    stage-packages:
      - openjdk-8-jre-headless
      - librxtx-java
      - fontconfig
      - fontconfig-config
      - libfontconfig1
      - x11-xserver-utils
      - curl
      - tar
      - python3
      - python3-requests
      - ca-certificates
      - ca-certificates-java    
      - libpango-1.0-0
      
  launcher:
    plugin: dump
    source: scripts
    
  cleanup:
    after:
      - tool
      - launcher
    plugin: nil
    build-snaps: 
      - core20
      - gnome-3-34-1804
    override-prime: |
      set -eux
      for snap in "core20" "gnome-3-34-1804"; do  # List all content-snaps and base snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done  
