name: tunerstudio
adopt-info: tunerstudio
summary: TunerStudio MS - an advanced MegaSquirt Tuning Software
description: |
  TunerStudio MS, the most most advanced and refined MegaSquirt Tuning software available.
  The registered and Lite! editions are the same installer. 
  
  BETA edition.

  After installing, run the following commands:
  
  sudo snap connect tunerstudio:raw-usb
  sudo snap connect tunerstudio:removable-media
  sudo snap connect tunerstudio:bluez
  sudo snap connect tunerstudio:bluetooth-control
  
  This is NOT an officially supported snap from TunerStudio. 

base: core20
grade: stable
confinement: strict
compression: lzo

assumes: 
  - command-chain
  
architectures:
  - build-on: amd64

apps:
  tunerstudio: 
    extensions: 
      - gnome-3-38
    command: launch
    command-chain: 
      - bin/homeishome-launch    
    plugs:
      - network
      - network-bind
      - home
      - raw-usb
      - removable-media
      - browser-support
      - audio-playback
      - pulseaudio  # compatibility with snapd <2.41
      - x11
      - desktop
      - desktop-legacy
      - bluez
      - bluetooth-control
    environment: 
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64
      JRE_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64/jre  
      
parts:
  tunerstudio:    
    plugin: nil
    override-build: |     
      #VARS
      ################################
      TAR=$(curl -s "https://www.efianalytics.com/TunerStudio/beta/" | grep "tar.gz" | head -n1 | cut -d '"' -f2)
      ################################
      mkdir -p BUILD
      cd BUILD/
      wget -O tunerstudio.tar.gz https://www.efianalytics.com/TunerStudio/beta/${TAR}
      tar -xzvf tunerstudio.tar.gz
      rm tunerstudio.tar.gz
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin/
      cp -r * $SNAPCRAFT_PART_INSTALL/bin/

    override-pull: |    
      snapcraftctl pull
      snapcraftctl set-version $(curl -s "https://www.efianalytics.com/TunerStudio/beta/" | grep "tar.gz" | head -n1 | cut -d '"' -f2 | cut -d "_" -f2 | sed 's/v//')
      
      
    build-packages:
      - wget
      - tar
      - awk
      - sed
      - curl
      
    stage-packages:
      - openjdk-11-jdk
      - openjdk-11-jre
      - librxtx-java
      - fontconfig
      - fontconfig-config
      - libfontconfig1
      - x11-xserver-utils
      - libgtk-3-dev   
      - ca-certificates-java
      - ca-certificates               

    stage:
    - -usr/lib/jvm/java-11-openjdk-*/lib/security/cacerts
    - -usr/lib/jvm/java-11-openjdk-*/lib/security/blacklisted.certs 

  homeishome-launch:
    plugin: nil
    stage-snaps:
      - homeishome-launch         
            
  launcher:
    plugin: dump
    source: scripts
    
   
  cleanup:
    after:
      - tunerstudio
      - launcher
    plugin: nil
    build-snaps: 
      - core20
      - gnome-3-38-2004
    
