name: tunerstudio
adopt-info: tunerstudio
summary: TunerStudio MS - an advanced MegaSquirt Tuning Software
description: |
  TunerStudio MS, the most most advanced and refined MegaSquirt Tuning software available.
  The registered and Lite! editions are the same installer. 
  
  After installing, run the following commands:
  
  sudo snap connect tunerstudio:raw-usb
  sudo snap connect tunerstudio:removable-media
  sudo snap connect tunerstudio:bluez
  sudo snap connect tunerstudio:bluetooth-control
  
  This is NOT an officially supported snap from TunerStudio. 

base: core24
grade: stable
confinement: strict
compression: lzo
icon: snap/gui/tunerstudio.png
license: Proprietary
contact: https://www.tunerstudio.com/
website: https://www.tunerstudio.com/
issues: https://github.com/kz6fittycent/TunerStudio-snap/issues
source-code: https://github.com/kz6fittycent/TunerStudio-snap

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]

apps:
  tunerstudio: 
    extensions: 
      - gnome
    command: launch
    plugs:
      - network
      - network-bind
      - home
      - raw-usb
      - removable-media
      - browser-support
      - audio-playback
      - pulseaudio  # compatibility with snapd <2.41
      - x11
      - desktop
      - desktop-legacy
      - bluez
      - bluetooth-control
    environment: 
      JAVA_HOME: $SNAP/usr/lib/jvm/java-17-openjdk-amd64
      JRE_HOME: $SNAP/usr/lib/jvm/java-17-openjdk-amd64/jre  
      
parts:
  tunerstudio:    
    plugin: nil
    override-build: |     
      #VARS
      ################################
      TAR=$(curl -s "https://www.efianalytics.com/TunerStudio/download/" | grep "tar.gz" | head -n1 | cut -d '"' -f2)
      ################################
      mkdir -p BUILD
      cd BUILD/
      wget -O tunerstudio.tar.gz https://www.efianalytics.com/TunerStudio/download/${TAR}
      tar -xzvf tunerstudio.tar.gz
      rm tunerstudio.tar.gz
      mkdir -p $CRAFT_PART_INSTALL/bin/
      cp -r * $CRAFT_PART_INSTALL/bin/

    override-pull: |    
      craftctl default
      craftctl set version=$(curl -s "https://www.efianalytics.com/TunerStudio/download/" | grep "tar.gz" | head -n1 | cut -d '"' -f2 | cut -d "_" -f2 | sed 's/v//' | sed 's/.tar.gz//')
      
    build-packages:
      - wget
      - tar
      - gawk
      - sed
      - curl
      
    stage-packages:
      - openjdk-17-jdk
      - openjdk-17-jre
      - librxtx-java
      - fontconfig
      - fontconfig-config
      - libfontconfig1
      - x11-xserver-utils
      - libgtk-3-dev   
      - ca-certificates-java
      - ca-certificates               

    stage:
    - -usr/lib/jvm/java-17-openjdk-*/lib/security/cacerts
    - -usr/lib/jvm/java-17-openjdk-*/lib/security/blacklisted.certs 
            
  launcher:
    plugin: dump
    source: scripts
       
  cleanup:
    after:
      - tunerstudio
      - launcher
    plugin: nil
    build-snaps: 
      - core24
